spring:
  application:
    name: gfi-asset-inventory

  datasource:
    url: jdbc:mysql://localhost:3306/gfi-asset-tracker?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
